
windowrule = match:class QQ ,float on 
windowrule = match:class QQ ,match:title QQ, tile on
# windowrule = float,class:wechat

windowrule = match:class wechat, match:title wechat, tile on
#去掉hyprland 边框
windowrule = border_size 0, match:class ^(wechat)$, match:title negative:^(朋友圈)$, match:title negative:^(微信)$
#去掉hyprland模糊效果
windowrule = no_blur on, match:class ^(wechat)$,match:title negative:^(朋友圈)$,match:title negative:^(微信)$
#去掉hyprland 阴影效果
windowrule = no_shadow on, match:class ^(wechat)$, match:title negative:^(朋友圈)$, match:title negative:^(微信)$
windowrule = float on,match:class steam
windowrule = tile on,match:class steam,match:title steam

windowrule = float on,match:initial_class Godot, match:initial_title negative:^(Godot)$


workspace = 1, monitor:eDP-1, default:true, on-created-empty:[tire] kitty -e timer_rs -c & kitty -e cava & kitty -e gtop
workspace = 2, monitor:eDP-1, default:true, on-created-empty:[tire] chromium
workspace = 3, monitor:eDP-1, default:true, on-created-empty:[tire] kitty
workspace = 4, monitor:eDP-1, default:true, on-created-empty:[tire] lutris
workspace = 5, monitor:eDP-1, default:true, on-created-empty:[tire] /opt/QQ/qq & wechat
