
$monitor=eDP-1
$monitor2=DP-1
workspace = 1, monitor:$monitor, layout:dwindle, default:true, on-created-empty:[tire] kitty -e timer_rs -c & kitty -e cava & kitty -e gtop
workspace = 2, monitor:$monitor, default:true, on-created-empty:[tire] chromium
workspace = 3, monitor:$monitor, default:true, on-created-empty:[tire] kitty
workspace = 4, monitor:$monitor, default:true, on-created-empty:[tire] lutris
workspace = 5, monitor:$monitor, default:true, on-created-empty:[tire] linuxqq & wechat

